version: "3"

services:
    postgres:
        image: postgres:14.2
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: heroes 
        volumes:
            - ./.docker/data/postgres:/var/lib/postgresql

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres

