version: "3"

services:

## PostgreSQL
    postgres:
        image: postgres:14.2
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: heroes 
        volumes:
            - ./.docker/data/postgres:/var/lib/postgresql

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres

## MongoDB
    mongodb:
        image: mongo:4.4.4
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: heroes
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - ./.docker/data/mongodb:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        # restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root